/**
 * v3.3 Cost Lens — terminal + Markdown formatters.
 *
 * Two output modes:
 *   1. Terminal one-liner / table — used by `engram cost` and `--watch`.
 *   2. Markdown digest — used by `engram cost --digest`, written to
 *      ~/.engram/cost-report-YYYY-WW.md and pipeable to Telegram/Substack.
 */
import { CostSummary, ProjectCostRow } from "./types.js";

export function formatNumber(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(2)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return String(Math.round(n));
}

export function formatUsd(n: number): string {
  if (n >= 1) return `$${n.toFixed(2)}`;
  if (n >= 0.01) return `$${n.toFixed(3)}`;
  return `$${n.toFixed(4)}`;
}

export function formatPct(ratio: number): string {
  return `${(ratio * 100).toFixed(1)}%`;
}

export function formatOneLine(s: CostSummary): string {
  return [
    `${formatNumber(s.tokensSaved)} tokens saved`,
    `${formatPct(s.reductionRatio)} reduction`,
    `~${formatUsd(s.approxUsdSaved)}`,
    `${s.events} events`,
  ].join(" · ");
}

export function formatTable(rows: ProjectCostRow[]): string {
  if (rows.length === 0) return "(no projects with hook-log.jsonl)";
  const lines: string[] = [];
  lines.push("Project                            Tokens saved   Reduction   Approx USD   Events");
  lines.push("─".repeat(86));
  for (const r of rows) {
    const name = truncate(basenameOf(r.projectRoot), 32).padEnd(34);
    const saved = formatNumber(r.summary.tokensSaved).padStart(13);
    const pct = formatPct(r.summary.reductionRatio).padStart(11);
    const usd = formatUsd(r.summary.approxUsdSaved).padStart(12);
    const ev = String(r.summary.events).padStart(7);
    lines.push(`${name}${saved}   ${pct}   ${usd}   ${ev}`);
  }
  return lines.join("\n");
}

export function formatMarkdownDigest(
  rows: ProjectCostRow[],
  totals: CostSummary,
  isoWeek: string
): string {
  const lines: string[] = [];
  lines.push(`# Engram Cost Digest — ${isoWeek}`);
  lines.push("");
  lines.push(`**Total tokens saved:** ${formatNumber(totals.tokensSaved)} `
    + `(${formatPct(totals.reductionRatio)} reduction, `
    + `~${formatUsd(totals.approxUsdSaved)})`);
  lines.push("");
  lines.push("## Per-project");
  lines.push("");
  lines.push("| Project | Tokens saved | Reduction | Approx USD | Events |");
  lines.push("|---|---:|---:|---:|---:|");
  for (const r of rows) {
    lines.push([
      "",
      basenameOf(r.projectRoot),
      formatNumber(r.summary.tokensSaved),
      formatPct(r.summary.reductionRatio),
      formatUsd(r.summary.approxUsdSaved),
      String(r.summary.events),
      "",
    ].join("|"));
  }
  lines.push("");
  lines.push("_Generated by `engram cost --digest` (v3.3 Cost Lens)_");
  return lines.join("\n");
}

function basenameOf(p: string): string {
  const idx = Math.max(p.lastIndexOf("/"), p.lastIndexOf("\\"));
  return idx >= 0 ? p.slice(idx + 1) : p;
}
function truncate(s: string, n: number): string {
  return s.length <= n ? s : `${s.slice(0, n - 1)}…`;
}
